### ISSUE TITLE
Window freezing for interaction constantly... but I can see new messages arriving in it!

### ISSUE THREAD

**Issue by hradec** [ShadyThGod/altus#29] opened 2019-07-05 22:06 UTC
This is happening to me constantly. I just installed Altus using the appimage, and it seems to work fine until I add my whatsapp account. After that, the window freezes and I can't click on anything... nothing happens. 

Weirdly enough, I see new messages arriving to me... So it seems the UI is updating and running, but I can't interact with it!

By disabling the custom titlebar, I'm able to access the menu (since now its the system window menu). But everything below the menu remains frozen for interaction, either by using the mouse or keyboard! 

I'm running Arch Linux, with Deepin desktop.

here a gif of the problem: 
![deepin-screen-recorder_Select area_20190705160027](https://user-images.githubusercontent.com/806743/60747971-3b1c2600-9f3e-11e9-9d7f-3b1c9471bf65.gif)

Here is another example where I actually can interact with the UI while whatsapp is loading... as soon as the whatsapp UI comes up behind the setting window, the UI freezes and I can't interact anymore, not even to close the setting window. 
![deepin-screen-recorder_Select area_20190705160229](https://user-images.githubusercontent.com/806743/60748018-99490900-9f3e-11e9-88ad-0fd817027822.gif)

_Originally posted by @hradec in https://github.com/ShadyThGod/altus/issues/27#issuecomment-508870726_

**Comment by ShadyThGod** [comment] 2019-07-06 04:44
This seems to be a very random bug. Because, I've been trying to reproduce this bug on Manjaro but only managed to do it once and I couldn't find out what caused it. If you have any way to reproduce this consistently then please let me know.

**Comment by hradec** [comment] 2019-07-06 07:15
Well... for me it happens EVERY SINGLE TIME! I can't use Altus at all..

**Comment by hradec** [comment] 2019-07-07 00:09
> This seems to be a very random bug. Because, I've been trying to reproduce this bug on Manjaro but only managed to do it once and I couldn't find out what caused it. If you have any way to reproduce this consistently then please let me know.

I would suggest you to try on Arch Linux, with Deepin desktop installed instead of Manjaro. 
Or you can try to install Deepin in Manjaro... but I'm not sure if it works... Manjaro is not a 100% Arch, as far as I known...

**Comment by hradec** [comment] 2019-07-07 00:14
I'm trying to find some information about this type of issue with electron/appimage, but no luck so far. 

It almost looks like a deadlock when the app shows the whatsapp UI (which I'm guessing it's just the actual web app from whatsapp, correctly?)

I've ran it with a Altus.2.3.2.AppImage.config folder to examine what Altus create, and there's some references inside about chromium... so am I right on guessing Altus is using chromium to show the whatsapp web app? 

If so, maybe chromium is not receiving the focus from Altus for some reason... 

my 2 cents...

**Comment by hradec** [comment] 2019-07-07 00:35
hoo... I'm seeing the same running it inside an x11docker of a debian distro running lxde desktop: 
![image](https://user-images.githubusercontent.com/806743/60762341-7556f780-a012-11e9-84e2-0625d673e7a8.png)

Since x11docker runs a completely separately x11 server using xephyr, means Altus is running as if it was in debian lxde. 

I'm preparing a one-liner for you to run x11docker and try for yourself... I'm wondering if it's going to work for you... which would indicate the problem is Arch with Deepin specific.

**Comment by hradec** [comment] 2019-07-07 01:50
Although pretty long, this one liner will run lxde inside a docker container using [x11docker](https://github.com/mviereck/x11docker)

```
docker pull x11docker/lxde ; mkdir /tmp/altus_test ; x11docker --verbose --user=root --desktop --size 1600x900 -- "-v /tmp/altus_test/:/root/ --privileged --cap-add SYS_ADMIN --cap-add MKNOD --device /dev/fuse" x11docker/lxde /bin/bash -c 'apt -y install libnss3 fuse ; echo deb http://ftp.ca.debian.org/debian/ buster main contrib non-free | tee -a /etc/apt/sources.list ; apt -y update ; apt -y install wget ;  cd ; wget "https://github.com/ShadyThGod/altus/releases/download/2.3.2/Altus.2.3.2.AppImage" ; chmod a+x *.AppImage ; startlxde  & ./*.AppImage'
```

it will use /tmp/altus_test as home folder, and download the Appimage and run it inside lxde. You should see Altus popping up as soon as lxde loads up!

**Comment by hradec** [comment] 2019-07-07 02:01
Ok... I think I figured something new now... 
In x11docker/lxde, if I add my whatsapp without changing anything in the options (like notification or theme), Altus work as expected!!
![deepin-screen-recorder_Select area_20190706184743](https://user-images.githubusercontent.com/806743/60762963-4004d680-a01f-11e9-8b94-9dca0faea579.gif)

and then, if I change the theme after it's working like above, this is the result: 
![deepin-screen-recorder_Select area_20190706185413](https://user-images.githubusercontent.com/806743/60762981-8c501680-a01f-11e9-915c-d7164a38501c.gif)

After that, even if I change the theme back to the default, it always freezes!!!!

So, as long as I just add an account and don't change anything, it works!! 

I tested on my normal linux Arch with Deepin, and it also works if I don't change anything! 
![deepin-screen-recorder_Select area_20190706185658](https://user-images.githubusercontent.com/806743/60763009-2748f080-a020-11e9-9293-34d35c3b34e3.gif)
But as you can see at the end of the gif, as soon as I change the theme, it freezes and always freezes, even after closing and opening again.

The only way to fix it, is delete the ~/.config/altus folder, and re-configure Altus without changing anything!! 

Hope that helps for you to reproduce the problem!!

**Comment by ShadyThGod** [comment] 2019-07-07 05:08
This might have possibly something to do with how the themes/settings are applied. I will look into that as soon as possible.

**Comment by timonoj** [comment] 2019-08-18 10:51
Any updates? I've seen recent updates since, but this keeps happening. This issue with the dark theme makes it unusable for many of us. I can't use Altus as it is right now.

**Comment by ShadyThGod** [comment] 2019-08-18 13:42
@timonoj Unfortunately not. I've not been able to recreate this on any of my machines which is making it harder for me to debug this.

**Comment by timonoj** [comment] 2019-08-20 00:23
Maybe you can try a VM with KDE? I'm using KDE Neon. Initially it works for
a bit with a brand new setup. But it will crash after 10mins, to never work
again. I set it with dark mode, it was all working nice and fine...but then
somehow it stopped after a bit, and I can't do anything to fix it.

**Comment by joaodurante** [comment] 2019-08-24 21:14
I'm facing the same issue. But the window freeze's more frequently and easier, sometimes it starts freezed. I'm using Pop_OS distro.

**Comment by ShadyThGod** [comment] 2019-08-25 06:42
I think [v1.2.4](https://github.com/ShadyThGod/altus/releases/tag/1.2.4) should work correctly for everyone. It is an older version which is very basic (but still has theming support) and it still works. Can you guys try it out?

**Comment by ShadyThGod** [comment] 2019-08-25 09:21
I have just released [v1.3.0](https://github.com/ShadyThGod/altus/releases/tag/1.3.0) which is based of an older version, but with additional changes. This version doesn't have multiple account support, but it does have almost every other feature. Theses issues shouldn't occur in v1.3.0

**Comment by joaodurante** [comment] 2019-08-25 17:46
Hey friend, I tested this version and apparently it's working fine. Made some tests that I did in the others versions and this one doesn't frozen in any time.
Thanks

**Comment by timonoj** [comment] 2019-09-02 09:53
I also can confirm after a few days of usage, the issue with the theme freezing the window is gone in this older version. All good here! Just on KDE, the tray icon doesn't seem to update if there's new messages. Not sure if that's a feature to be added at a later stage.

Thanks!

**Comment by ShadyThGod** [comment] 2019-11-01 23:56
Should be fixed in [v3.0](https://github.com/ShadyThGod/altus/releases/tag/3.0.0). Please test it out and let me know.

**Comment by joaodurante** [comment] 2019-11-02 00:46
Nice, I will test it as soon as possible.
Thank you friend

**Comment by ShadyThGod** [comment] 2019-11-05 16:08
Closing this issue as I think the issue is fixed and I haven't gotten any new reports.

**Closed by ShadyThGod** 2019-11-05 16:08 UTC
Labels: bug, help wanted
