### ISSUE TITLE
Design is fucked

### ISSUE THREAD

**Issue by panteLx** [ShadyThGod/altus#25] opened 2019-05-28 22:11 UTC
Hi,
Since the last WA update my design is fucked :3 it hurts in my eyes

https://i.imgur.com/cXBpYaL.png

**Comment by ShadyThGod** [comment] 2019-05-29 07:33
Could you tell me in a little more detail about what's wrong with this?

**Comment by panteLx** [comment] 2019-05-29 09:30
since the last wa update the dark design isnt longer dark :) only the msg bubbles are dark, the rest isnt.

**Comment by ShadyThGod** [comment] 2019-05-29 09:33
Just saw that. I'm going to have to update the theme now.. Don't worry I'll update it in a day or two.

**Comment by ShadyThGod** [comment] 2019-05-30 06:21
Should be fixed now. If you use the inbuilt dark theme, go to `Theme`>`Manage Themes` (or press `CmdOrCtrl+T`) and then click `Update Dark Theme`. If you use a custom dark theme, you will have to re-create that using the Theme Customizer.

**Closed by ShadyThGod** 2019-05-30 06:21 UTC

**Comment by ShadyThGod** [comment] 2019-05-30 06:26
I'm going to keep updating the theme as soon as find anything that needs to be fixed. So if something isn't fixed, just use the above method to update the theme.

**Comment by panteLx** [comment] 2019-05-30 20:55
https://i.imgur.com/A3Dcq5I.png another styling bug :P only on business accs with shortcuts. 
Also if you tag someone the color of that person isnt like the other link text color

**Comment by ShadyThGod** [comment] 2019-05-31 07:38
@panteLx I don't have a business account so I can't reproduce this on my pc.

Could you recreate this in Chrome (web.whatsapp.com) and then using Inspect Element, try to fix it? I assume you have some experience HTML/CSS. Here are the color variables you can use:
```
--dark: #272c35;
--darker: #1F232A;
--light: #D1D1D1;
--lighter: #E9E9E9;
--accent: #7289DA;
```
If you manage to fix it, comment the element selectors and the colors you used here.

**Comment by panteLx** [comment] 2019-05-31 22:52
I really want to but I cant cause the select field always disappears if I try to select it with inspect element... 
I'm just able to figure out which parent div it is but not its child div cause its hidden by default.

Parent div: _**Ya_1h**_

**Comment by ShadyThGod** [comment] 2019-06-01 07:56
I was having the same issue with one of the other menu disappearing when inspecting.
What you can do is use `MutationObserver`. Here is the code (put this in the DevTools console) :

```js
observer = new MutationObserver(function(mutations){
    mutations.forEach(function(mutation){
        console.log(mutation)
    })
});
observer.observe(document.documentElement, { childList: true, subtree: true })
```

This will keep logging elements that were added/removed. You will then need to go through the list to find the element. I recommend trying to put the styles on every element in the list sequentially and then seeing which one actually applies the theme.

**Comment by panteLx** [comment] 2019-06-01 13:52
puh bro cant figure out which child div it is :D sorry

**Comment by ShadyThGod** [comment] 2019-06-01 13:53
Well, then, there's not much that can be done. I don't have any means to fix this :/
